local packer = require('packer')

packer.startup(function()
	-- Define your plugins using Packer.nvim's use() function
	packer.use('dense-analysis/ale')
	packer.use('jason0x43/vim-js-indent')
	packer.use('Quramy/vim-js-pretty-template')
	packer.use('andrewradev/splitjoin.vim')
	-- packer.use('mxw/vim-jsx')  -- Commented out example
	packer.use('jparise/vim-graphql')
	packer.use('pantharshit00/vim-prisma')
	-- packer.use('sheerun/vim-polyglot')  -- Commented out example
	packer.use('tomlion/vim-solidity')
	packer.use('ryanolsonx/vim-xit')
	packer.use('evanleck/vim-svelte', { branch = 'main' })
	packer.use('stefandtw/quickfix-reflector.vim')
	packer.use('jremmen/vim-ripgrep')
	packer.use('junegunn/fzf', { dir = '~/.fzf', run = './install --all' })
	packer.use('junegunn/fzf.vim')
	packer.use('editorconfig/editorconfig-vim')
	packer.use('easymotion/vim-easymotion')
	packer.use('itchyny/lightline.vim')
	packer.use('tpope/vim-surround')
	packer.use('scrooloose/nerdtree')
	packer.use('tpope/vim-commentary')
	packer.use('JoosepAlviste/nvim-ts-context-commentstring')
	packer.use('nvim-treesitter/nvim-treesitter', { run = ':TSUpdate' })
	packer.use('cormacrelf/vim-colors-github')
	packer.use('tpope/vim-fugitive')
end)
